### ISSUE TITLE
Revisit DPP/Gateway listing in the service detail view

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma-gui#1443] opened 2023-09-05 14:11 UTC
### Description

Continuation of https://github.com/kumahq/kuma-gui/issues/1347

Service detail 'proxy listings' should be able to either show:

1. Only DPPs
2. Only Gateways
3. If the end user has configured things incorrectly then it is possible that we can see both DPPs and Gateways in the listing

Whereas currently we assume these are always sidecars/DPPs.

We should try to optimize for the correct configuration, but also show some sort of warning to the user if the user has configured things wrong (i.e. we get a mix of DPPs and gateways in the response)

Options (not exhaustive)

1. Use two tabs, _but generally we only ever show one tab_, but in the case of user configuration error we show both tabs with some sort of warning. As we won't know which type (DPPs/Gateways) is 'unwanted' we just word this as "its incorrect as there is a mix".
2. Make the listing able to "cope" with both types of proxies, again if we detect a mix we show an error.
3. I think there was some chat on knowing what type of proxies to expect using the service insight endpoint. If we can do this then we could choose which type of listing to show, and also only request those specific proxies (using `gateway=true/false`), alternatively if we continue to request all proxies we would know if there is a user error by detecting if there are gateways in the case of a sidecar type service, or vice versa.

Feel free to edit/add if I've missed anything.

**Comment by kleinfreund** [comment] 2023-09-20 13:56
Just wanted to make note of the fact that we currently have logic in this view that reads `dataplanesData?.items?.[0]?.dataplane?.networking?.gateway` in order to determine whether we’re looking at gateways or DPPs. If that key is present, we treat _all_ entries as gateways; otherwise, DPPs. That’s something we need to take into account and get right when working on this.

**Comment by johncowen** [comment] 2023-11-01 10:30
This one has been sat here for a while and there have been quite a few related problems that keep appearing that are related to this. My thinking is we should just make this list in Services cope with both types of proxies, they almost have the same properties anyway.

We can then add a warning as a second step as a "nice to have".

**Comment by lahabana** [comment] 2023-11-06 10:38
Duplicate of #1717

**Closed by lahabana** 2023-11-06 10:38 UTC
Labels: triage/accepted, kind/feature, kind/design
