### ISSUE TITLE
Kubernetes representation isn’t correct for new resources that already have spec field

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma-gui#423] opened 2022-10-26 12:51 UTC
### What happened?

Kubernetes representation isn’t correct for new resources that already have spec field. *Then*, spec shouldn’t appear twice in the resulting YAML.

Needs backend work (https://github.com/kumahq/kuma/issues/6658) to tell GUI whether a resource uses new format.

**Comment by slonka** [comment] 2023-05-02 09:21
@kleinfreund can you link to the backend issue for this?

**Comment by kleinfreund** [comment] 2023-05-02 12:14
@slonka I don’t think there is a backend issue for this, yet.

**Comment by slonka** [comment] 2023-05-02 13:00
Can you make one?

**Comment by kleinfreund** [comment] 2023-05-02 13:03
@slonka Here you go: https://github.com/kumahq/kuma/issues/6658

**Comment by lahabana** [comment] 2023-05-11 08:30
Duplicate of #696

**Closed by lahabana** 2023-05-11 08:30 UTC
Labels: triage/accepted, kind/bug
