### ISSUE TITLE
Provide more documentation / options on customizing MeshGatewayInstance

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma-gui#1640] opened 2023-10-22 18:43 UTC
### Description

Might be desirable to set node selectors for example

**Comment by jakubdyszkiewicz** [comment] 2023-10-23 14:16
Duplicate of https://github.com/kumahq/kuma/issues/4903
It's not possible to customize node selectors

**Closed by jakubdyszkiewicz** 2023-10-23 14:16 UTC
Labels: triage/pending, kind/feature
